/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unipar.panel;

import br.unipar.Menu;
import br.unipar.api.VendaAPI;
import br.unipar.exceptions.ErrorException;
import br.unipar.frame.PesquisarClienteFrame;
import br.unipar.frame.PesquisarProdutoFrame;
import br.unipar.models.Cliente;
import br.unipar.models.ItemVenda;
import br.unipar.models.Produto;
import br.unipar.models.Venda;
import br.unipar.tablemodels.ItemVendaTableModel;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author victo
 */
public class VendaPanel extends JPanel {

    /**
     * Creates new form VendaPanel
     */
    Cliente cliente;
    Produto produto;
    List<ItemVenda> listaProdutos = new ArrayList<>();
    ItemVendaTableModel model;

    public VendaPanel() {
        initComponents();
        atualizarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        tfProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        tfVlUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfVlTotal = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        btRemover = new javax.swing.JButton();
        tfTotalVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObservacao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel5.setText("Cliente:");

        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteKeyReleased(evt);
            }
        });

        tfProduto.setToolTipText("");
        tfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfProdutoKeyReleased(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Quantidade");

        tfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyReleased(evt);
            }
        });

        tfVlUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVlUnitarioKeyReleased(evt);
            }
        });

        jLabel3.setText("Valor Unit");

        jLabel4.setText("Valor Total");

        tfVlTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfVlTotalKeyReleased(evt);
            }
        });

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btFinalizar.setText("Finalizar");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProdutos);

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        taObservacao.setColumns(20);
        taObservacao.setRows(5);
        jScrollPane1.setViewportView(taObservacao);

        jLabel6.setText("Observações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(tfVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAdicionar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemover)
                    .addComponent(tfTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfClienteKeyPressed(KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteKeyPressed

    private void tfClienteKeyReleased(KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            JFrame clienteFrame = new PesquisarClienteFrame(this, tfCliente.getText().toLowerCase());
            tfCliente.setText("");
            abrirFrame(clienteFrame);
        }
    }//GEN-LAST:event_tfClienteKeyReleased

    private void tfProdutoKeyReleased(KeyEvent evt) {//GEN-FIRST:event_tfProdutoKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            JFrame produFrame = new PesquisarProdutoFrame(this, tfProduto.getText().toLowerCase());
            tfProduto.setText("");
            abrirFrame(produFrame);
        }
    }//GEN-LAST:event_tfProdutoKeyReleased

    private void btFinalizarActionPerformed(ActionEvent evt) {
        salvarVenda();
    }

    private void btCancelarActionPerformed(ActionEvent evt) {
        if(listaProdutos.isEmpty() && tfCliente.getText().isEmpty() && tfProduto.getText().isEmpty()){
            SwingUtilities.getWindowAncestor(this).dispose();

            Menu menu = new Menu();
            menu.setVisible(true);
        }else{
            limparCampos();
        }
    }

    private void btRemoverActionPerformed(ActionEvent evt) {
        if(!listaProdutos.isEmpty()){
            listaProdutos.remove(model.getSelectedItem(jTableProdutos, listaProdutos));
            atualizarTable();
        }
    }

    private void tfQuantidadeKeyReleased(KeyEvent evt) {
        atualizarValores();
    }

    private void tfVlUnitarioKeyReleased(KeyEvent evt) {
        atualizarValores();
    }

    private void tfVlTotalKeyReleased(KeyEvent evt) {
        atualizarValores();
    }

    private void btAdicionarActionPerformed(ActionEvent evt) {
        try {
            validarCamposProduto();
            adicionarProduto();
        } catch (ErrorException e) {
            throw new RuntimeException(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextArea taObservacao;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfProduto;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfTotalVenda;
    private javax.swing.JTextField tfVlTotal;
    private javax.swing.JTextField tfVlUnitario;
    // End of variables declaration//GEN-END:variables

    private void abrirFrame(JFrame frame){
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void retornarCliente(Cliente cliente){
        if(cliente!=null){
            this.cliente = cliente;
            tfCliente.setText(cliente.getNome());
        }
    }

    public void retornarProduto(Produto produto){
        if(produto!=null){
            this.produto = produto;
            atualizarCamposProduto();
        }
    }

    private void atualizarCamposProduto(){
        tfProduto.setText(produto.getDescricao());
        tfQuantidade.setText("1");
        tfVlUnitario.setText(String.valueOf(produto.getValor()));
        tfVlTotal.setText(String.valueOf(produto.getValor()*1));
    }

    private void atualizarValores(){
        double vlrTotal = Integer.parseInt(tfQuantidade.getText()) * Double.parseDouble(tfVlUnitario.getText());
        tfVlTotal.setText(String.valueOf(vlrTotal));
    }

    private void validarCamposProduto() throws ErrorException {
        if(tfProduto==null){
            tfProduto.requestFocus();
            JOptionPane.showMessageDialog(this, "Informe um produto para adicioanr", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            throw new ErrorException("Informe um produto");
        }
        if(tfQuantidade.getText().isEmpty() || tfQuantidade.getText()=="0"){
            tfQuantidade.requestFocus();
            JOptionPane.showMessageDialog(this, "Informe a quantidade do produto", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            throw new ErrorException("Informe uma quantidade");
        }
        if(tfVlUnitario.getText().isEmpty() || tfVlUnitario.getText()=="0"){
            tfVlUnitario.requestFocus();
            JOptionPane.showMessageDialog(this, "Informe um valor", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            throw new ErrorException("Informe o valor");
        }
        if(tfVlTotal.getText().isEmpty() || tfVlTotal.getText()=="0"){
            tfVlTotal.requestFocus();
            JOptionPane.showMessageDialog(this, "Informe um valor total", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            throw new ErrorException("Informe um valor total");
        }
    }

    private void limparCamposProduto(){
        tfProduto.setText("");
        produto = null;
        tfQuantidade.setText("");
        tfVlUnitario.setText("");
        tfVlTotal.setText("");
    }

    private void limparCampos(){
        produto = null;
        cliente=null;
        tfCliente.setText("");
        listaProdutos.clear();
        model = new ItemVendaTableModel();
        jTableProdutos.setModel(model);
        tfProduto.setText("");
        tfQuantidade.setText("");
        tfVlUnitario.setText("");
        tfVlTotal.setText("");
        tfTotalVenda.setText("");
    }

    private void adicionarProduto(){
        ItemVenda iv = new ItemVenda();

        iv.setProduto(produto);
        iv.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
        iv.setVlUnitario(Double.parseDouble(tfVlUnitario.getText()));
        iv.setVlTotal(Double.parseDouble(tfVlTotal.getText()));

        listaProdutos.add(iv);

        double totalVenda = 0;
        for(int i = 0; i<listaProdutos.size();i++){
            totalVenda += listaProdutos.get(i).getVlTotal();
        }
        tfTotalVenda.setText(String.valueOf(totalVenda));

        limparCamposProduto();
        atualizarTable();
    }

    private void atualizarTable(){
        model = new ItemVendaTableModel(listaProdutos);
        jTableProdutos.setModel(model);
    }

    private void salvarVenda(){
        VendaAPI dao = new VendaAPI();
        Venda venda = new Venda();

        venda.setCliente(cliente);
        venda.setDtVenda(new Date());
        venda.setVlTotal(Double.parseDouble(tfTotalVenda.getText()));
        venda.setObservacao(taObservacao.getText());
        List<ItemVenda> lista = listaProdutos;
        venda.setListaProdutos(lista);


        dao.insert(venda);
        limparCampos();
    }
}
